# SwiftLint Configuration for Spatial Wellness Platform

# Opt-in rules
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity

# Included paths
included:
  - SpatialWellness/Sources
  - SpatialWellness/Tests

# Excluded paths
excluded:
  - Pods
  - .build
  - SpatialWellness/.build
  - landing-page
  - docs

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1200
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

# File header
file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*?\.swift
                    \/\/ Spatial Wellness Platform
                    \/\/
                    \/\/ Created on .*?
                    \/\/

# Custom rules
custom_rules:
  # Require @MainActor for view models
  mainactor_viewmodel:
    name: "ViewModel MainActor"
    regex: 'class\s+\w+ViewModel(?!.*@MainActor)'
    message: "ViewModels should be marked with @MainActor"
    severity: warning

  # Require access control
  explicit_access_control:
    name: "Explicit Access Control"
    regex: '(class|struct|enum)\s+\w+'
    message: "Types should have explicit access control (public, internal, private)"
    severity: warning

  # Avoid force unwrapping in production code
  force_unwrap:
    name: "Force Unwrapping"
    regex: '\!\s'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping. Use optional binding instead"
    severity: error
    excluded:
      - ".*Tests\\.swift"

  # Require documentation for public APIs
  public_documentation:
    name: "Public API Documentation"
    regex: 'public\s+(func|var|let|class|struct|enum)(?!.*\/\/\/)'
    message: "Public APIs should have documentation comments"
    severity: warning

# Analyzer rules (requires --analyze flag)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Reporter type
reporter: "xcode"
