# SwiftLint Configuration for Field Service AR
# visionOS 2.0+ | Swift 6.0

# Rules to enable
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # We use TODO comments for tracking
  - line_length # Handled by formatter

# Rule configurations
file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  statement_level: 5

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*\.swift
                    \/\/ Field Service AR Assistant
                    \/\/
                    \/\/ Created .* on \d{4}-\d{2}-\d{2}\.
                    \/\/

# Paths to include/exclude
included:
  - FieldServiceAR

excluded:
  - Pods
  - DerivedData
  - .build
  - vendor
  - Carthage
  - node_modules
  - Package.swift

# Reporter type
reporter: "xcode"

# Warnings as errors
strict: false

# Analyze
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "print\\("
    message: "Use Logger instead of print()"
    severity: warning

  no_force_unwrap:
    name: "No force unwrapping"
    regex: "\\!(?!\\s*=)"
    message: "Avoid force unwrapping - use optional binding or guard"
    severity: warning
    excluded: ".*Tests\\.swift"

  proper_spacing_after_comment:
    name: "Space after comment slashes"
    regex: "//\\w"
    message: "Add space after // in comments"
    severity: warning

  mark_format:
    name: "MARK format"
    regex: "//\\s*MARK:(?!\\s*-)"
    message: "MARK should be followed by a space and dash: // MARK: -"
    severity: warning

  no_swiftdata_main_actor:
    name: "SwiftData operations off main actor"
    regex: "@MainActor.*(?:modelContext|ModelContext)"
    message: "SwiftData operations should use @ModelActor, not @MainActor"
    severity: error
    excluded: ".*View\\.swift"

  visionos_api_check:
    name: "visionOS 2.0+ API availability"
    regex: "@available\\(visionOS 1"
    message: "Use visionOS 2.0+ APIs"
    severity: warning
