# SwiftLint Configuration for Financial Trading Dimension

# Rule Configuration
disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # We track TODOs in issues

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Paths
included:
  - FinancialTradingDimension

excluded:
  - Pods
  - FinancialTradingDimension/Resources
  - .build
  - DerivedData
  - build

# File Header
file_header:
  required_pattern: |
    \/\/
    \/\/  .*?\.swift
    \/\/  Financial Trading Dimension
    \/\/
    \/\/  Created.*
    \/\/

# Rules Configuration

# Line Length
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function Body Length
function_body_length:
  warning: 50
  error: 100

# Function Parameter Count
function_parameter_count:
  warning: 6
  error: 8

# Type Body Length
type_body_length:
  warning: 300
  error: 400

# File Length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Cyclomatic Complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Nesting
nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

# Identifier Name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - r
    - g
    - b
    - a
    - i
    - j
    - k

# Type Name
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - T
    - U
    - V

# Large Tuple
large_tuple:
  warning: 3
  error: 4

# Multiple Closures with Trailing Closure
multiple_closures_with_trailing_closure:
  severity: warning

# Number Separator
number_separator:
  minimum_length: 5

# Object Literal
object_literal:
  image_literal: false
  color_literal: false

# Vertical Whitespace
vertical_whitespace:
  max_empty_lines: 2

# Custom Rules
custom_rules:
  # No direct use of print statements (use logger instead)
  no_print:
    name: "No Print Statements"
    regex: '(?<!//)\sprint\('
    match_kinds:
      - identifier
    message: "Use logger instead of print for production code"
    severity: warning

  # Prefer guard for early returns
  prefer_guard:
    name: "Prefer Guard for Early Returns"
    regex: 'if\s+.*\{\s*return'
    message: "Consider using guard for early returns"
    severity: warning

  # No force unwrapping in production code
  no_force_unwrap:
    name: "No Force Unwrapping"
    regex: '!\s*(?!(is|as))'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping - use optional binding or guard"
    severity: error
    excluded: ".*Tests?\\.swift"

  # No force cast
  no_force_cast:
    name: "No Force Cast"
    regex: 'as!'
    message: "Avoid force casting - use conditional casting (as?)"
    severity: error
    excluded: ".*Tests?\\.swift"

  # Require explicit self for capturing
  explicit_self_in_closures:
    name: "Explicit Self in Closures"
    regex: '\{\s*\[.*\bin\b.*self\.'
    message: "Use explicit self in closures that capture self"
    severity: warning

  # Mark comments
  mark_comment:
    name: "Mark Comment Format"
    regex: '//\s*MARK:\s*(?![A-Z])'
    message: "MARK comments should start with a capital letter"
    severity: warning

  # TODO format
  todo_format:
    name: "TODO Format"
    regex: '//\s*TODO:\s*(?![A-Z])'
    message: "TODO comments should start with a capital letter and include a ticket number"
    severity: warning

  # FIXME format
  fixme_format:
    name: "FIXME Format"
    regex: '//\s*FIXME:\s*(?![A-Z])'
    message: "FIXME comments should start with a capital letter and include a ticket number"
    severity: warning

# Reporter
reporter: "xcode"

# Analyzer Rules (requires compilation)
analyzer_rules:
  - unused_declaration
  - unused_import
