# SwiftLint Configuration for Language Immersion Rooms

# Paths to include/exclude
included:
  - LanguageImmersionRooms
  - LanguageImmersionRoomsTests

excluded:
  - Pods
  - .build
  - DerivedData
  - docs

# Rules
disabled_rules:
  - trailing_whitespace # Handled by formatter
  - todo # Allow TODO comments

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule Configurations

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - AI

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - rx
    - ry
    - rz
    - dx
    - dy
    - dz
    - to
    - db
    - vm
    - os

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Custom Rules

custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use proper logging instead of print()"
    severity: warning
    match_kinds:
      - identifier

  no_force_try:
    name: "No Force Try"
    regex: "try!"
    message: "Use proper error handling instead of try!"
    severity: error

  no_force_cast:
    name: "No Force Cast"
    regex: " as!"
    message: "Use conditional casting (as?) instead of force casting (as!)"
    severity: warning

  no_nslog:
    name: "No NSLog"
    regex: "NSLog\\("
    message: "Use Swift's print() or proper logging framework"
    severity: warning

  copyright_header:
    name: "Copyright Header"
    regex: "^//\\n//  \\w+\\.swift\\n//  Language Immersion Rooms"
    message: "Files should have proper copyright header"
    severity: warning
    match_kinds:
      - comment

# Reporter
reporter: "xcode" # Options: xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging
