//
//  FileServiceTests.swift
//  Molecular Design Platform Tests
//
//  Unit tests for FileService (MDL, SDF, PDB, XYZ parsers)
//

import XCTest
import SwiftData
@testable import MolecularDesignPlatform

final class FileServiceTests: XCTestCase {
    var fileService: FileService!
    var molecularService: MolecularService!
    var modelContext: ModelContext!
    var chemistryEngine: ChemistryEngine!
    var tempDirectory: URL!

    override func setUp() async throws {
        // Create in-memory model container
        let schema = Schema([Molecule.self, Project.self, Simulation.self, Experiment.self])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: schema, configurations: [config])
        modelContext = ModelContext(container)

        chemistryEngine = ChemistryEngine()
        molecularService = MolecularService(modelContext: modelContext, chemistryEngine: chemistryEngine)
        fileService = FileService(molecularService: molecularService)

        // Create temp directory for test files
        tempDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("MolecularDesignPlatformTests_\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDirectory, withIntermediateDirectories: true)
    }

    override func tearDown() async throws {
        // Clean up temp directory
        try? FileManager.default.removeItem(at: tempDirectory)

        fileService = nil
        molecularService = nil
        modelContext = nil
        chemistryEngine = nil
        tempDirectory = nil
    }

    // MARK: - MDL Molfile Tests

    func testMDLMolfileExport() async throws {
        // Create a simple molecule (methane: CH4)
        let carbon = Atom(element: .carbon, position: .zero)
        let h1 = Atom(element: .hydrogen, position: SIMD3<Float>(1.0, 0, 0))
        let h2 = Atom(element: .hydrogen, position: SIMD3<Float>(-1.0, 0, 0))
        let h3 = Atom(element: .hydrogen, position: SIMD3<Float>(0, 1.0, 0))
        let h4 = Atom(element: .hydrogen, position: SIMD3<Float>(0, -1.0, 0))

        let bond1 = Bond(atom1: carbon.id, atom2: h1.id)
        let bond2 = Bond(atom1: carbon.id, atom2: h2.id)
        let bond3 = Bond(atom1: carbon.id, atom2: h3.id)
        let bond4 = Bond(atom1: carbon.id, atom2: h4.id)

        let molecule = Molecule(
            name: "Methane",
            atoms: [carbon, h1, h2, h3, h4],
            bonds: [bond1, bond2, bond3, bond4]
        )

        // Export to MDL file
        let fileURL = tempDirectory.appendingPathComponent("methane.mol")
        try await fileService.exportMolecule(molecule, to: fileURL, format: .mdl)

        // Verify file was created
        XCTAssertTrue(FileManager.default.fileExists(atPath: fileURL.path))

        // Read and verify content
        let content = try String(contentsOf: fileURL)
        XCTAssertTrue(content.contains("Methane"))
        XCTAssertTrue(content.contains("  5  4"))  // 5 atoms, 4 bonds
        XCTAssertTrue(content.contains("M  END"))
    }

    func testMDLMolfileImportExportRoundTrip() async throws {
        // Create sample molfile content
        let molfileContent = """
        Ethanol
          Generated by Test

          3  2  0  0  0  0  0  0  0  0999 V2000
            -1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
             0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
             1.5000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
          1  2  1  0  0  0  0
          2  3  1  0  0  0  0
        M  END
        """

        // Write test file
        let inputURL = tempDirectory.appendingPathComponent("test_ethanol.mol")
        try molfileContent.write(to: inputURL, atomically: true, encoding: .utf8)

        // Import
        let molecule = try await fileService.importMolecule(from: inputURL)

        XCTAssertEqual(molecule.atoms.count, 3)
        XCTAssertEqual(molecule.bonds.count, 2)

        // Export again
        let outputURL = tempDirectory.appendingPathComponent("output_ethanol.mol")
        try await fileService.exportMolecule(molecule, to: outputURL, format: .mdl)

        // Verify round-trip
        let exportedContent = try String(contentsOf: outputURL)
        XCTAssertTrue(exportedContent.contains("  3  2"))  // Same atom/bond count
    }

    // MARK: - SDF Tests

    func testSDFExport() async throws {
        // Create molecule with properties
        let carbon = Atom(element: .carbon, position: .zero)
        let oxygen = Atom(element: .oxygen, position: SIMD3<Float>(1.5, 0, 0))
        let bond = Bond(atom1: carbon.id, atom2: oxygen.id, order: .double)

        let molecule = Molecule(
            name: "Carbon Monoxide",
            atoms: [carbon, oxygen],
            bonds: [bond]
        )

        // Add properties
        molecule.properties = MolecularProperties()
        molecule.properties?.logP = 0.5
        molecule.properties?.tpsa = 20.5
        molecule.properties?.hbd = 0
        molecule.properties?.hba = 1

        // Export to SDF
        let fileURL = tempDirectory.appendingPathComponent("test.sdf")
        try await fileService.exportMolecule(molecule, to: fileURL, format: .sdf)

        // Verify content
        let content = try String(contentsOf: fileURL)
        XCTAssertTrue(content.contains("$$$$"))  // SDF delimiter
        XCTAssertTrue(content.contains("> <LogP>"))
        XCTAssertTrue(content.contains("> <TPSA>"))
    }

    func testSDFImport() async throws {
        // Create SDF file with multiple molecules
        let sdfContent = """
        Molecule1
          Test

          2  1  0  0  0  0  0  0  0  0999 V2000
            0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
            1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
          1  2  1  0  0  0  0
        M  END
        > <LogP>
        1.23

        > <MW>
        30.07

        $$$$
        """

        let fileURL = tempDirectory.appendingPathComponent("multi.sdf")
        try sdfContent.write(to: fileURL, atomically: true, encoding: .utf8)

        // Import
        let molecule = try await fileService.importMolecule(from: fileURL)

        XCTAssertEqual(molecule.atoms.count, 2)
        XCTAssertEqual(molecule.bonds.count, 1)
        XCTAssertFalse(molecule.tags.isEmpty)  // Should have property tags
    }

    func testSDFMultipleMolecules() async throws {
        // Create SDF with two molecules
        let sdfContent = """
        Mol1
          Test

          1  0  0  0  0  0  0  0  0  0999 V2000
            0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        M  END
        $$$$
        Mol2
          Test

          1  0  0  0  0  0  0  0  0  0999 V2000
            0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        M  END
        $$$$
        """

        let fileURL = tempDirectory.appendingPathComponent("two_mols.sdf")
        try sdfContent.write(to: fileURL, atomically: true, encoding: .utf8)

        // Import multiple
        let molecules = try await fileService.importMolecules(from: fileURL)

        XCTAssertEqual(molecules.count, 2)
        XCTAssertEqual(molecules[0].atoms.count, 1)
        XCTAssertEqual(molecules[1].atoms.count, 1)
    }

    // MARK: - PDB Tests

    func testPDBExport() async throws {
        // Create a simple molecule
        let carbon = Atom(element: .carbon, position: SIMD3<Float>(1.0, 2.0, 3.0))
        let nitrogen = Atom(element: .nitrogen, position: SIMD3<Float>(4.0, 5.0, 6.0))
        let oxygen = Atom(element: .oxygen, position: SIMD3<Float>(7.0, 8.0, 9.0))

        let molecule = Molecule(
            name: "Test Protein",
            formula: "CNO",
            atoms: [carbon, nitrogen, oxygen],
            bonds: []
        )

        // Export to PDB
        let fileURL = tempDirectory.appendingPathComponent("test.pdb")
        try await fileService.exportMolecule(molecule, to: fileURL, format: .pdb)

        // Verify content
        let content = try String(contentsOf: fileURL)
        XCTAssertTrue(content.contains("HEADER"))
        XCTAssertTrue(content.contains("COMPND"))
        XCTAssertTrue(content.contains("ATOM"))
        XCTAssertTrue(content.contains("END"))

        // Check coordinates are present
        XCTAssertTrue(content.contains("1.000"))
        XCTAssertTrue(content.contains("2.000"))
        XCTAssertTrue(content.contains("3.000"))
    }

    func testPDBImport() async throws {
        // Create sample PDB file
        let pdbContent = """
        HEADER    TEST MOLECULE
        ATOM      1  C   MOL A   1       1.000   2.000   3.000  1.00  0.00           C
        ATOM      2  N   MOL A   1       4.000   5.000   6.000  1.00  0.00           N
        END
        """

        let fileURL = tempDirectory.appendingPathComponent("test.pdb")
        try pdbContent.write(to: fileURL, atomically: true, encoding: .utf8)

        // Import
        let molecule = try await fileService.importMolecule(from: fileURL)

        XCTAssertEqual(molecule.atoms.count, 2)
        XCTAssertEqual(molecule.atoms[0].element, .carbon)
        XCTAssertEqual(molecule.atoms[1].element, .nitrogen)

        // Bonds should be inferred
        XCTAssertFalse(molecule.bonds.isEmpty)
    }

    // MARK: - XYZ Tests

    func testXYZExport() async throws {
        // Create simple molecule
        let hydrogen1 = Atom(element: .hydrogen, position: SIMD3<Float>(0.0, 0.0, 0.0))
        let hydrogen2 = Atom(element: .hydrogen, position: SIMD3<Float>(0.74, 0.0, 0.0))

        let molecule = Molecule(
            name: "Hydrogen gas",
            atoms: [hydrogen1, hydrogen2],
            bonds: []
        )

        // Export to XYZ
        let fileURL = tempDirectory.appendingPathComponent("h2.xyz")
        try await fileService.exportMolecule(molecule, to: fileURL, format: .xyz)

        // Verify content
        let content = try String(contentsOf: fileURL)
        let lines = content.components(separatedBy: .newlines)

        XCTAssertEqual(lines[0], "2")  // Number of atoms
        XCTAssertTrue(lines[1].contains("Hydrogen"))  // Comment line
        XCTAssertTrue(lines[2].hasPrefix("H"))  // First atom
        XCTAssertTrue(lines[3].hasPrefix("H"))  // Second atom
    }

    func testXYZImport() async throws {
        // Create XYZ file
        let xyzContent = """
        3
        Water molecule
        O  0.000000  0.000000  0.000000
        H  0.757000  0.586000  0.000000
        H -0.757000  0.586000  0.000000
        """

        let fileURL = tempDirectory.appendingPathComponent("water.xyz")
        try xyzContent.write(to: fileURL, atomically: true, encoding: .utf8)

        // Import
        let molecule = try await fileService.importMolecule(from: fileURL)

        XCTAssertEqual(molecule.name, "Water molecule")
        XCTAssertEqual(molecule.atoms.count, 3)
        XCTAssertEqual(molecule.atoms[0].element, .oxygen)
        XCTAssertEqual(molecule.atoms[1].element, .hydrogen)
        XCTAssertEqual(molecule.atoms[2].element, .hydrogen)

        // Bonds should be inferred
        XCTAssertGreaterThan(molecule.bonds.count, 0)
    }

    // MARK: - Error Handling Tests

    func testUnsupportedFormatError() async throws {
        let fileURL = tempDirectory.appendingPathComponent("test.unknown")

        do {
            _ = try await fileService.importMolecule(from: fileURL)
            XCTFail("Should throw unsupported format error")
        } catch let error as FileServiceError {
            switch error {
            case .unsupportedFormat(let ext):
                XCTAssertEqual(ext, "unknown")
            default:
                XCTFail("Wrong error type")
            }
        }
    }

    func testInvalidFileContent() async throws {
        // Create invalid molfile
        let invalidContent = "This is not a valid molfile"
        let fileURL = tempDirectory.appendingPathComponent("invalid.mol")
        try invalidContent.write(to: fileURL, atomically: true, encoding: .utf8)

        do {
            _ = try await fileService.importMolecule(from: fileURL)
            XCTFail("Should throw invalid file error")
        } catch is FileServiceError {
            // Expected error
            XCTAssertTrue(true)
        }
    }

    func testEmptyFile() async throws {
        let fileURL = tempDirectory.appendingPathComponent("empty.mol")
        try "".write(to: fileURL, atomically: true, encoding: .utf8)

        do {
            _ = try await fileService.importMolecule(from: fileURL)
            XCTFail("Should throw error for empty file")
        } catch {
            // Expected
            XCTAssertTrue(true)
        }
    }

    // MARK: - Bond Inference Tests

    func testBondInference() async throws {
        // Create XYZ with two carbon atoms close together
        let xyzContent = """
        2
        Ethane fragment
        C  0.000  0.000  0.000
        C  1.540  0.000  0.000
        """

        let fileURL = tempDirectory.appendingPathComponent("ethane.xyz")
        try xyzContent.write(to: fileURL, atomically: true, encoding: .utf8)

        let molecule = try await fileService.importMolecule(from: fileURL)

        // Should infer C-C bond (covalent radii sum ~1.52 Å, actual distance 1.54 Å)
        XCTAssertEqual(molecule.bonds.count, 1, "Should infer one C-C bond")
    }

    func testNoBondInferenceForDistantAtoms() async throws {
        // Create XYZ with atoms far apart
        let xyzContent = """
        2
        Distant atoms
        C   0.0  0.0  0.0
        C  10.0  0.0  0.0
        """

        let fileURL = tempDirectory.appendingPathComponent("distant.xyz")
        try xyzContent.write(to: fileURL, atomically: true, encoding: .utf8)

        let molecule = try await fileService.importMolecule(from: fileURL)

        // Should not infer any bonds (too far)
        XCTAssertEqual(molecule.bonds.count, 0, "Should not infer bonds for distant atoms")
    }
}
