# SwiftLint Configuration for Supply Chain Control Tower

# Included paths
included:
  - App
  - Models
  - Views
  - ViewModels
  - Services
  - Utilities
  - Tests

# Excluded paths
excluded:
  - .build
  - Resources
  - build

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments during development
  - line_length # Handled by Xcode formatting

# Rule configurations
type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - db
    - vm
    - i
    - j
    - k

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

large_tuple:
  warning: 3
  error: 4

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SupplyChainControlTower.*
                    \/\/

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_cast:
    name: "No force casts"
    regex: "as!"
    message: "Use optional casting (as?) or conditional casting instead"
    severity: error

  proper_async_await:
    name: "Use async/await for asynchronous code"
    regex: "DispatchQueue\\.(main|global)"
    message: "Prefer async/await over DispatchQueue"
    severity: warning

# Reporter
reporter: "xcode"

# Warnings as errors
strict: false

# Violations to ignore in test files
excluded_test_rules:
  - force_unwrapping
  - force_try
  - function_body_length
  - type_body_length
