# SwiftLint Configuration for Tactical Team Shooters

# Paths
included:
  - TacticalTeamShooters
excluded:
  - .build
  - Packages
  - Tests
  - scripts

# Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - trailing_whitespace  # Let editor handle this
  - todo  # We use TODOs for tracking

# Rule Configuration

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

type_name:
  min_length: 3
  max_length: 50

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

# Custom Rules

custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '(?<!// )print\('
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_cast:
    name: "No Force Casts"
    regex: ' as! '
    message: "Use safe casting with 'as?' instead"
    severity: error

  no_force_unwrap:
    name: "No Force Unwrapping"
    regex: '!\s*(?![=,\)])'
    message: "Use safe unwrapping instead of force unwrapping"
    severity: warning

# Reporter
reporter: "xcode"
