# SwiftLint Configuration for Living Building System
# https://github.com/realm/SwiftLint

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - Packages
  - docs
  - landing-page

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # Allow TODO comments during development
  - line_length # Overly restrictive for documentation

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations

# Naming rules
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

# Length rules
function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

# Complexity rules
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

# Force rules (allow force unwrap in tests)
force_cast:
  severity: warning
force_try:
  severity: warning
force_unwrapping:
  severity: warning

# Custom rules
custom_rules:
  # Ensure print statements are not committed
  no_print_statements:
    name: "No Print Statements"
    regex: '(?<!#if\s+DEBUG\n)print\('
    message: "Use Logger instead of print() for production code"
    severity: warning

  # Ensure proper spacing around operators
  proper_operator_spacing:
    name: "Proper Operator Spacing"
    regex: '\S(=|\+|-|\*|\/|\%)\S'
    message: "Operators should have spaces around them"
    severity: warning

  # Discourage force unwrapping in production code
  avoid_force_unwrap_production:
    name: "Avoid Force Unwrap in Production"
    regex: '(?<!Tests).*!\s*$'
    message: "Avoid force unwrapping in production code"
    match_kinds:
      - identifier
    severity: warning

  # Ensure TODO/FIXME have assignee
  todo_with_assignee:
    name: "TODO with Assignee"
    regex: '\/\/\s*(TODO|FIXME)(?!\(\w+\))'
    message: "TODOs and FIXMEs should include an assignee: // TODO(username): description"
    severity: warning

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, markdown, github-actions-logging)
reporter: "xcode"

# Warnings as errors (for CI)
# strict: true  # Uncomment for strict enforcement

# Performance optimizations
compilation_mode: wholemodule
