# SwiftLint Configuration for Holographic Board Games

# Rule Configuration
disabled_rules:
  - trailing_whitespace  # Allow trailing whitespace in comments
  - todo  # Allow TODO comments during development

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Paths
included:
  - HolographicBoardGames/HolographicBoardGames
  - HolographicBoardGames/HolographicBoardGamesTests

excluded:
  - Pods
  - .build
  - .swiftpm
  - DerivedData
  - HolographicBoardGames/HolographicBoardGames/App/Info.plist

# Metrics
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

# Naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Custom Rules
custom_rules:
  no_objc_inference:
    name: "No @objc Inference"
    regex: '@objc\s+(?!dynamic)'
    message: "Use @objc only when necessary"
    severity: warning

  no_direct_ui_main:
    name: "No Direct DispatchQueue.main"
    regex: 'DispatchQueue\.main\.'
    match_kinds: identifier
    message: "Consider using @MainActor instead of DispatchQueue.main"
    severity: warning
    excluded: ".*Tests\\.swift"

# Reporter
reporter: "xcode"
