import { GoogleGenerativeAI } from "@google/generative-ai";
import { saveFile, generateFilename } from "../utils.js";

interface VeoOptions {
  duration?: number; // 5-15 seconds
  aspectRatio?: "9:16" | "16:9" | "1:1";
}

interface VeoResult {
  path: string;
}

export async function generateVideoVeo(
  prompt: string,
  options: VeoOptions = {}
): Promise<VeoResult> {
  if (!process.env.GOOGLE_API_KEY) {
    throw new Error("GOOGLE_API_KEY not set in environment variables");
  }

  const { duration = 8, aspectRatio = "16:9" } = options;

  console.error(`Generating video with Veo 3.1: "${prompt}"`);

  const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY);

  // Initialize model with system instruction
  const model = genAI.getGenerativeModel({
    model: "veo-3.1",
    systemInstruction: `Generate a ${duration}-second video in ${aspectRatio} aspect ratio.`
  });

  // Generate video using Gemini API with Veo
  const result = await model.generateContent({
    contents: [
      {
        role: "user",
        parts: [
          {
            text: prompt,
          },
        ],
      },
    ],
  });

  // Extract video data from response
  const response = result.response;
  const candidates = response.candidates;

  if (!candidates || candidates.length === 0) {
    throw new Error("No video generated by Veo 3.1");
  }

  // Get the video part from the response
  const videoPart = candidates[0].content.parts.find(
    (part: any) => part.inlineData?.mimeType?.startsWith("video/")
  );

  if (!videoPart || !videoPart.inlineData) {
    throw new Error("No video data in Veo 3.1 response");
  }

  // Convert base64 video to buffer
  const videoBuffer = Buffer.from(videoPart.inlineData.data, "base64");

  // Save to file
  const filename = generateFilename("veo3", "mp4");
  const filepath = await saveFile(videoBuffer, filename);

  console.error(`Video saved to: ${filepath}`);

  return {
    path: filepath,
  };
}
