# SwiftLint Configuration for Surgical Training Universe
# https://realm.github.io/SwiftLint/

# Paths to include in linting
included:
  - SurgicalTrainingUniverse

# Paths to ignore
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - SurgicalTrainingUniverse/Resources
  - "*/Generated"
  - "**/*+CoreDataProperties.swift"

# Disabled Rules
disabled_rules:
  - trailing_whitespace # Can be too strict
  - todo # Allow TODO comments during development
  - line_length # Handled by custom rule

# Opt-in Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule Configurations

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 7

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
  allowed_symbols: ["_"]

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
  allowed_symbols: []

large_tuple:
  warning: 3
  error: 4

# Custom Line Length
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

# Number of arguments
function_parameter_count:
  warning: 6
  error: 8

# Trailing closure
trailing_closure:
  only_single_muted_parameter: true

# Force unwrap configuration
force_unwrapping:
  severity: warning

# Force cast configuration
force_cast:
  severity: warning

# Force try configuration
force_try:
  severity: warning

# Implicitly unwrapped optional
implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets

# Multiple closures with trailing closure
multiple_closures_with_trailing_closure:
  severity: warning

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# File header
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SurgicalTrainingUniverse

# Trailing comma
trailing_comma:
  mandatory_comma: false

# Closure parameter position
closure_parameter_position:
  severity: warning

# Colon spacing
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

# Comment spacing
comment_spacing:
  severity: warning

# Opening brace spacing
opening_brace:
  severity: warning

# Return arrow whitespace
return_arrow_whitespace:
  severity: warning

# Statement position
statement_position:
  severity: warning
  statement_mode: default

# Unused optional binding
unused_optional_binding:
  severity: warning
  ignore_optional_try: false

# Custom Rules
custom_rules:
  # Prefer private over fileprivate
  prefer_private:
    name: "Prefer private over fileprivate"
    regex: "fileprivate"
    message: "Use private instead of fileprivate when possible"
    severity: warning

  # No direct use of print
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning

  # SwiftUI view size limit
  view_size_limit:
    name: "SwiftUI View Size"
    regex: "(?:var|let)\\s+body:\\s*some\\s+View\\s*\\{(?:[^{}]*|\\{[^{}]*\\}){200,}\\}"
    message: "SwiftUI body should be broken into smaller views"
    severity: warning

# Analyzer Rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Reporter
reporter: "xcode" # xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging
