# SwiftLint Configuration for Narrative Story Worlds

# Paths to include in linting
included:
  - NarrativeStoryWorlds

# Paths to exclude from linting
excluded:
  - Pods
  - Carthage
  - DerivedData
  - .build
  - Package.swift
  - NarrativeStoryWorlds/Tests/Fixtures

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # We track TODOs in GitHub Issues

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - AI

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - a
    - b
    - c
    - r
    - g
    - b
    - i
    - j
    - k
    - to
    - at

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 6

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Custom rules
custom_rules:
  # Require MARK comments for type organization
  mark_sections:
    name: "MARK Sections"
    regex: '(class|struct|enum|extension)\s+\w+[^{]*\{(?!.*\/\/\s*MARK:)'
    message: "Types should be organized with MARK: comments"
    severity: warning

  # Discourage print statements (use proper logging)
  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use proper logging instead of print()"
    severity: warning
    match_kinds:
      - identifier

  # Require documentation for public APIs
  public_docs:
    name: "Public API Documentation"
    regex: '(public|open)\s+(class|struct|enum|func|var|let)(?!.*\/\/\/)'
    message: "Public APIs should have documentation comments"
    severity: warning

  # Discourage force unwrapping
  force_unwrap:
    name: "Force Unwrap Discouraged"
    regex: '!\s*(?!(=|<|>|\?|:))'
    message: "Avoid force unwrapping - use if let, guard let, or nil coalescing"
    severity: warning
    excluded: ".*Tests\\.swift"

  # Require explicit self for clarity in closures
  explicit_self_in_closures:
    name: "Explicit Self in Closures"
    regex: '\{\s*\[(?:weak|unowned)\s+self\]\s+.*\s+\w+\s*=.*(?!self\.)'
    message: "Use explicit self in closures to clarify captures"
    severity: warning

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  NarrativeStoryWorlds
                    \/\/

# Reporter type
reporter: "xcode"

# Warnings as errors (strict mode)
strict: false

# Allow warnings
warnings_as_errors: false
