# SwiftLint Configuration
# Home Maintenance Oracle

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - operator_usage_whitespace

included:
  - HomeMaintenanceOracle

excluded:
  - Pods
  - Build
  - DerivedData
  - .build

# Rule Configurations

line_length:
  warning: 120
  error: 150
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - url
    - URL
    - i
    - j
    - x
    - y
    - z

force_cast: warning
force_try: warning

# Custom Rules

custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use proper logging instead of print statements"
    severity: warning
