# SwiftLint configuration for Reality Realms RPG
# For more information, see: https://github.com/realm/SwiftLint

# Rules that are enabled by default
enabled_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_length
  - equality_comparison_to_none
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - file_header
  - file_length
  - file_name
  - file_name_no_space
  - first_where
  - flat_map_over_map_reduce
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - format_string_validation
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - invalid_swiftlint_directive
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - macro_spacing
  - mark_spacing
  - match_focus_keyword
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - mutating_func_parameter_kind
  - native_pair_coding
  - nested_parentheses
  - nesting
  - never_force_unwrap
  - no_space_in_method_call
  - nsobject_prefer_isequal
  - number_separator
  - object_literal_length
  - one_declaration_per_line
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - optional_returns_on_newline
  - orphaned_task
  - overridden_super_call
  - override_in_extension
  - package_name
  - pattern_matching_keywords
  - period_spacing
  - prefer_key_path
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_unowned
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - raw_value_returning_initializer
  - reduce_boolean_expression
  - reduce_into
  - redundant_bool_comparison
  - redundant_discardable_let
  - redundant_deinitialization
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_self
  - redundant_string_enum_value
  - redundant_type_annotation
  - region_identifier_and_nested_scope_level
  - required_deinit
  - required_enum_case
  - resource_bundle_reference
  - return_value_from_void_function
  - returning_whitespace
  - reverse_implied_ordering
  - reverse_optional_boolean
  - same_line_arguments_and_parameters
  - self_binding_in_unwrapped_optional_binding
  - self_in_property_initialization
  - semicolon
  - sentence_spacing
  - shorthand_optional_binding
  - single_test_class
  - size_class_elements
  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - spacing_around_operator
  - specified_selector
  - static_operator
  - static_over_final_class
  - statement_position
  - strict_fileprivate
  - string_literal_concatenation
  - string_spacing
  - struct_should_be_class
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - test_case_accessibility
  - todo
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - typesafe_array_init
  - uneven_indent
  - unhandled_throwing_task
  - union_of_ranges
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unneeded_synthesized_initializer
  - unneeded_override
  - unsafe_nserror_init
  - unsorted_enum_cases
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumeration
  - unused_import
  - unused_optional_binding
  - unused_parameter
  - unused_setter_value
  - upper_camel_case_name
  - valid_ibaction
  - valid_iboutlet
  - verbatim_regex_literal
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_function_in_ternary
  - void_return
  - weak_delegate
  - whitespace_around_func_params
  - xct_specific_matcher
  - yoda_condition
  - zone_avoid_hardcoded_numbers

# Rules that are disabled by default - include these if they should be enabled
opt_in_rules:
  - closure_body_length
  - comment_spacing
  - contains_over_filter_count
  - contains_over_first_not_nil
  - explicit_acl
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - expiring_todo
  - fatal_error_message
  - file_header
  - final_test_case
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - let_var_spacing
  - local_doc_comment
  - modifiers_order
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_unowned
  - raw_value_returning_initializer
  - reduce_into
  - redundant_type_annotation
  - required_deinit
  - required_enum_case
  - return_value_from_void_function
  - static_operator
  - switch_case_on_newline
  - test_case_accessibility
  - unhandled_throwing_task
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - weak_delegate
  - xct_specific_matcher

# Rules that are disabled
disabled_rules:
  - todo  # Allow TODO comments without dates
  - file_header  # Don't require file headers
  - vertical_whitespace  # Less strict vertical spacing
  - trailing_comma  # Allow trailing commas
  - collection_alignment  # Flexible collection alignment

# Configuration for specific rules

# Cyclomatic Complexity
cyclomatic_complexity:
  warning: 10
  error: 15

# File Length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Function Body Length
function_body_length:
  warning: 40
  error: 100

# Function Parameter Count
function_parameter_count:
  warning: 6
  error: 8
  ignores_default_parameters: true

# Identifier Name
identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 60
  allowed_symbols: "_"
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - a
    - b
    - c

# Indentation Width
indentation_width: 4

# Line Length
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false

# Nesting
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

# Type Body Length
type_body_length:
  warning: 250
  error: 350

# Type Name
type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 40
    error: 60
  excluded:
    - "HTTPSConnectionPool"
    - "HTTPConnectionPool"

# Large Tuple
large_tuple:
  warning: 3
  error: 4

# Enum Case Associated Values Length
enum_case_associated_values_length:
  warning: 5
  error: 6

# Number Separator
number_separator:
  minimum_length: 5

# Modifiers Order
modifiers_order:
  - override
  - open
  - public
  - package
  - internal
  - fileprivate
  - private
  - final
  - nonisolated
  - static
  - class
  - dynamic
  - mutating
  - nonmutating
  - convenience
  - required
  - weak
  - unowned
  - isolated
  - async
  - throws
  - throws(E)

# File Excludes
excluded:
  - Pods
  - Carthage
  - .build
  - Build
  - Generated
  - RealityRealms/Generated
  - RealityRealmsTests
  - RealityRealmsUITests

# Analyzer Rules (static analysis)
analyzer_rules:
  - unused_import
  - unused_declaration

# Custom Rules
custom_rules:
  no_hardcoded_api_keys:
    name: "No Hardcoded API Keys"
    regex: '(api[_-]?key|secret|password|token)\s*[=:]\s*["\']'
    message: "Do not hardcode API keys or secrets in source code"
    severity: error

  no_print_in_production:
    name: "No print() in Production Code"
    regex: 'print\('
    match_kinds: call
    message: "Use logger instead of print() for logging"
    severity: warning
    excluded_match_kinds: comment

# Reporter settings
reporter: "xcode"
